<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Taruns-MacBook-Air.local" failures="4" tests="4" name="EdgeTest" time="60.084" errors="0" timestamp="2025-08-29T00:10:35 PDT">
  <testcase classname="testCase.TC03_LoginDDT" name="verify_loginDDT" time="10.291">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCase.TC03_LoginDDT.verify_loginDDT(TC03_LoginDDT.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCase.TC03_LoginDDT" name="verify_loginDDT" time="12.127">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCase.TC03_LoginDDT.verify_loginDDT(TC03_LoginDDT.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCase.TC03_LoginDDT" name="verify_loginDDT" time="10.838">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCase.TC03_LoginDDT.verify_loginDDT(TC03_LoginDDT.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCase.TC03_LoginDDT" name="verify_loginDDT" time="10.866">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCase.TC03_LoginDDT.verify_loginDDT(TC03_LoginDDT.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- EdgeTest -->
